name: publish npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Exclude specific devDependencies
        run: |
          mv package.json package.json.tmp
          jq 'del(.devDependencies["@chromatic-com/storybook"], .devDependencies["@storybook/addon-essentials"], .devDependencies["@storybook/addon-interactions"], .devDependencies["@storybook/addon-links"], .devDependencies["@storybook/addon-onboarding"], .devDependencies["@storybook/blocks"], .devDependencies["@storybook/react"], .devDependencies["@storybook/react-vite"], .devDependencies["@storybook/test"], .devDependencies["@biomejs/biome"], .devDependencies["lint-staged"], .devDependencies["storybook"])' package.json.tmp > package.json

      - name: Install dependencies
        run: npm install

      - name: Restore original package.json
        run: mv package.json.tmp package.json

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
